FROM php:8.1-apache

RUN apt-get update \
    && apt-get install unzip -y

RUN docker-php-ext-install \
    mysqli \
    pdo_mysql

RUN php -r "readfile('https://getcomposer.org/installer');" | php \
    && mv composer.phar /usr/local/bin/composer

COPY ./src /var/www/html

RUN a2enmod rewrite

EXPOSE 80